[phases.setup]
nixPkgs = ["php82", "php82Packages.composer", "php82Packages.gd", "php82Packages.zip"]

[phases.build]
# Kita jalankan update agar Composer menyesuaikan diri dengan lingkungan server
cmds = ["composer update --no-dev --optimize-autoloader"]