[phases.setup]
nixPkgs = [
    "php82",
    "php82Packages.composer",
    "php82Packages.gd",
    "php82Packages.zip",
    "php82Packages.intl",
    "php82Packages.mbstring",
    "php82Packages.bcmath"
]

[phases.build]
cmds = ["composer install --no-dev --optimize-autoloader"]